# Generated by Django 5.2.5 on 2025-08-28 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Bien')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('codigo_patrimonial', models.CharField(max_length=50, unique=True, verbose_name='Código Patrimonial')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], default='disponible', max_length=20, verbose_name='Estado del Bien')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Bien Patrimonial',
                'verbose_name_plural': 'Bienes Patrimoniales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('bienes_asignados', models.ManyToManyField(blank=True, related_name='operadores', to='bienes.bien', verbose_name='Bienes Asignados')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Operador')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('administrador', 'Administrador'), ('operador', 'Operador')], default='operador', max_length=20, verbose_name='Tipo de Usuario')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
