# Generated by Django 5.2.5 on 2025-08-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='cuenta_codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cuenta / Código'),
        ),
        migrations.AddField(
            model_name='bien',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='bien',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Baja'),
        ),
        migrations.AddField(
            model_name='bien',
            name='tipo_origen',
            field=models.CharField(blank=True, choices=[('DONACION', 'Donación'), ('OMISION', 'Omisión'), ('TRANSFERENCIA', 'Transferencia/Traslado'), ('COMPRA', 'Compra')], max_length=20, verbose_name='Tipo de Origen'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Dado de baja'), ('TRANSFERIDO', 'Transferido'), ('MANTENIMIENTO', 'En mantenimiento')], default='ACTIVO', max_length=20, verbose_name='Estado del Bien'),
        ),
    ]
